### ISSUE TITLE
How to make a LAN server?

### ISSUE THREAD

**Issue by Kawaiikat14** [Spiderlover/Toontown-2#10]
Hi, I got the game to work but im having trouble making a lan server. 
Is it possible?
And if it is how?

**Comment by Spiderlover** [comment]
sorry, there's no lan support :)

**Comment by Kawaiikat14** [comment]
Will it possibly work on Hamachi?

**Comment by Spiderlover** [comment]
yeah, i think so. you have to change some stuff in astron and the config though

**Comment by Kawaiikat14** [comment]
Sounds complicated... You mind helping me

**Comment by Spiderlover** [comment]
I could, but I am busy

**Comment by Kawaiikat14** [comment]
Ok! Feel free to message me when you are available

**Comment by Virnios** [comment]
@Kawaiikat14 I can help you, You do not need to change ANYTHING, just as long as you two are connected to the same hamachi network it should all work fine, you start the game as normal. But he starts the game using the client and connects using your hamachi IP. Profit, really easy.

**Comment by Kawaiikat14** [comment]
@Virnios Ive tried that myself but sadly, No success

**Comment by Kawaiikat14** [comment]
Also. can i have a list of all the spellbook commands?

**Comment by Spiderlover** [comment]
you can do ~words in the game, but it will go off the screen since there are alot of commands in the game.

**Comment by Virnios** [comment]
@Kawaiikat14 What happens when you try? If it is a connection issue, try pinging each other on Hamachi, if neither of you get a reply from each other that's a whole new issue.

**Comment by Kawaiikat14** [comment]
@Virnios  Pinging works fine but when the other client on hamachi tries to get into the game, It refuses to connect.

**Comment by Kawaiikat14** [comment]
@Virnios also where would i put the IP adress for the client to connect? There is no entry in the clien launcher for IP

**Comment by Virnios** [comment]
You could change the IP of the current start_game.bat in dev/win32/start-game.bat,
If you change 
line 19, set TT_GAMESERVER=Toontown2.us.to to set TT_GAMESERVER=yourhamachiiphere
-THE FRIENDS YOU PLAY WITH MUST DO THIS, YOU DO NOT HAVE TO DO THIS.

**Comment by Virnios** [comment]
Then once you open the game after changing that, type in a username you want, same with your friends, do not use the same username.

**Comment by Kawaiikat14** [comment]
Ok now its working. But we are using seperate usernames and we keep getting DC

**Comment by Kawaiikat14** [comment]
Ok nevermind
The host computer uses option 1 in client launcher and the user uses option 2
Thanks for the help!

**Comment by Virnios** [comment]
You might not be connecting to the same server ._.

**Comment by Kawaiikat14** [comment]
No Its working

**Comment by Virnios** [comment]
Have fun!
