### ISSUE TITLE
Question: How to add a custom speedchat phrase to a new speedchat selection menu

### ISSUE THREAD

**Issue by Kawaiikat14** [Spiderlover/Toontown-2#15]
I would love to know how since I am very new to python coding. I see you guys made the Famous Quotes menu in this source, And i would like to know how to make one

**Comment by Spiderlover** [comment]
It is pretty simple, you have to declare the SpeedChat section and the phrases in OTPLocalizierEnglish.py, then you have to code the id numbers that the phrases are linked to for the SpeedChat section in TTChatInputSpeedChat.py

**Comment by Kawaiikat14** [comment]
Thanks And also do you know where the base file is for which automatically sets people to access level 700?

**Comment by Spiderlover** [comment]
in ClientServicesManagerUD.py which is in toontown/uberdog
