### ISSUE TITLE
Task Teleport Button

### ISSUE THREAD

**Issue by Snowballcps** [Spiderlover/Toontown-2#4]
Teleport button doesn't work when clicked in the Shticker Book, but does if you press when using 'End'.

**Comment by Spiderlover** [comment]
did you have the required jellybean amount to teleport?

**Comment by Snowballcps** [comment]
Yep. Clicking on the teleport button in the Shticker Book with 40 jellybeans in the jar doesn't trigger anything.

**Comment by Spiderlover** [comment]
interesting
