### ISSUE TITLE
TOONTOWN-2 QUESTIONS

### ISSUE THREAD

**Issue by mpchange** [Spiderlover/Toontown-2#5]
HALLO,

When ever this played: access level always at 700. Change in file -> back when REBOOT.

IN ADDITION

When reporting toon in game, how to deal report when created by normal!

THANK YOU!

HALLO ,

Wanneer ooit hierdie gespeel : toegang vlak altyd by 700. Verandering in lêer - > terug toe herlaai.

BENEWENS

Wanneer verslagdoening toon in 'n spel , hoe om verslag te doen wanneer geskep deur normale !

DANKIE!

**Comment by mpchange** [comment]
English friend

How do you prevent the access level from always being 700 when creating a toon, and how to prevent the access level from being modified when you manually change it back in the user file, and when the game is closed and opened again, the game will put the level back at 700.

Also, when a user reports something to a moderator via the toon gui, how does the moderator receive/handle that report.

**Comment by Spiderlover** [comment]
hello, the access level default setting is 700 because of the way it was coded. The report system is useless, since this is a single player/offline version of Toontown, and there are no moderators to review the reports anyways.

**Comment by mpchange** [comment]
Thank you for responding!

Is there any way to unset the 700 access level? How to do it?


Dankie vir die reageer jy !

Is daar enige manier om die 700 toegang vlak ontstel ? Hoe om dit te doen?

**Comment by Spiderlover** [comment]
no, you have to recode the entire section of code that controls it

**Comment by mpchange** [comment]
How hard?

**Comment by mpchange** [comment]
What file?

**Comment by Spiderlover** [comment]
it depends, i don't know what file it is located in

**Comment by mpchange** [comment]
Find?

**Comment by Virnios** [comment]
It is EXTREMELY, easy to change the access level you start with.

**Comment by mpchange** [comment]
What file? Want to start at good normal access user level for everyone and then me manually set to 700 if I want admin

**Comment by mpchange** [comment]
@Virnios

**Comment by mpchange** [comment]
Hello
